const handleFirebaseError = (errorCode) => {
  const errorMessages =
  
 {
    "auth/claims-too-large": "حجم بيانات المطالبات المقدمة لـ setCustomUserClaims() يتجاوز الحد الأقصى المسموح به وهو 1000 بايت.",
    "auth/email-already-exists": "البريد الإلكتروني المقدّم مستخدم بالفعل من قبل مستخدم موجود. يجب أن يكون لكل مستخدم بريد إلكتروني فريد.",
    "auth/id-token-expired": "رمز تعريف Firebase المقدم منتهي الصلاحية.",
    "auth/id-token-revoked": "تم إلغاء رمز تعريف Firebase.",
    "auth/insufficient-permission": "الإذن المستخدم لتفعيل SDK الإدارة غير كافٍ للوصول إلى مورد المصادقة المطلوب. راجع إعداد مشروع Firebase للحصول على الوثائق حول كيفية إنشاء إذن بالحقوق المناسبة واستخدامه لمصادقة SDK الإدارة.",
    "auth/invalid-argument": "تم تقديم وسيط غير صالح إلى طريقة المصادقة. يجب أن تحتوي رسالة الخطأ على معلومات إضافية.",
    "auth/invalid-claims": "سمات المطالبات المخصصة المقدمة لـ setCustomUserClaims() غير صالحة.",
    "auth/invalid-creation-time": "يجب أن تكون وقت الإنشاء سلسلة تاريخ UTC صالحة.",
    "auth/invalid-disabled-field": "القيمة المقدمة لخاصية المستخدم المعطلة غير صالحة. يجب أن تكون قيمة منطقية.",
    "auth/invalid-display-name": "القيمة المقدمة لخاصية displayName غير صالحة. يجب أن تكون سلسلة غير فارغة.",
    "auth/invalid-email-verified": "القيمة المقدمة لخاصية emailVerified غير صالحة. يجب أن تكون قيمة منطقية.",
    "auth/invalid-hash-algorithm": "يجب أن يتطابق خوارزمية التجزئة مع أحد السلاسل في قائمة الخوارزميات المدعومة.",
    "auth/invalid-hash-block-size": "يجب أن يكون حجم كتلة التجزئة رقمًا صالحًا.",
    "auth/invalid-hash-derived-key-length": "يجب أن يكون طول المفتاح المشتق من التجزئة رقمًا صالحًا.",
    "auth/invalid-hash-key": "يجب أن يكون مفتاح التجزئة مصفوفة بايت صالحة.",
    "auth/invalid-hash-memory-cost": "يجب أن تكون تكلفة الذاكرة لتجزئة القيم رقمًا صالحًا.",
    "auth/invalid-hash-parallelization": "يجب أن تكون التوازي في التجزئة رقمًا صالحًا.",
    "auth/invalid-hash-rounds": "يجب أن تكون جولات التجزئة رقمًا صالحًا.",
    "auth/invalid-hash-salt-separator": "يجب أن يكون حقل فاصل ملح خوارزمية التجزئة مصفوفة بايت صالحة.",
    "auth/invalid-id-token": "رمز التعريف المقدم ليس رمز تعريف Firebase صالحًا.",
    "auth/invalid-last-sign-in-time": "يجب أن تكون آخر وقت تسجيل دخول سلسلة تاريخ UTC صالحة.",
    "auth/invalid-page-token": "رمز الصفحة التالي المقدم في listUsers() غير صالح. يجب أن يكون سلسلة غير فارغة وصالحة.",
    "auth/invalid-password": "القيمة المقدمة لخاصية كلمة المرور غير صالحة. يجب أن تكون سلسلة بطول ستة أحرف على الأقل.",
    "auth/invalid-password-hash": "يجب أن تكون قيمة تجزئة كلمة المرور مصفوفة بايت صالحة.",
    "auth/invalid-password-salt": "يجب أن يكون ملح كلمة المرور مصفوفة بايت صالحة.",
    "auth/invalid-photo-url": "القيمة المقدمة لخاصية photoURL غير صالحة. يجب أن تكون عنوان URL كسلسلة.",
    "auth/invalid-provider-data": "يجب أن تكون providerData مصفوفة صالحة من كائنات UserInfo.",
    "auth/invalid-oauth-responsetype": "يجب تعيين نوع استجابة OAuth واحد فقط إلى true.",
    "auth/invalid-session-cookie-duration": "يجب أن تكون مدة ملف تعريف الارتباط للجلسة رقمًا صالحًا بالمللي ثانية بين 5 دقائق و 2 أسابيع.",
    "auth/invalid-uid": "يجب أن تكون القيمة المقدمة uid سلسلة غير فارغة تحتوي على ما يصل إلى 128 حرفًا.",
    "auth/invalid-user-import": "سجل المستخدم المراد استيراده غير صالح.",
    "auth/maximum-user-count-exceeded": "تم تجاوز الحد الأقصى المسموح به لعدد المستخدمين الذين يمكن استيرادهم.",
    "auth/missing-hash-algorithm": "يتطلب استيراد المستخدمين باستخدام تجزئة كلمات المرور تقديم خوارزمية التجزئة ومعلماتها.",
    "auth/missing-uid": "معرف uid مطلوب للعملية الحالية.",
    "auth/missing-oauth-client-secret": "السر العميل لتكوين OAuth مطلوب لتمكين تدفق رمز OIDC.",
    "auth/phone-number-already-exists": "رقم الهاتف المقدّم مستخدم بالفعل من قبل مستخدم موجود. يجب أن يكون لكل مستخدم رقم هاتف فريد.",
    "auth/project-not-found": "لم يتم العثور على مشروع Firebase للبيانات المستخدمة لتفعيل SDK الإدارة. راجع إعداد مشروع Firebase للحصول على الوثائق حول كيفية إنشاء إذن لمشروعك واستخدامه لمصادقة SDK الإدارة.",
    "auth/reserved-claims": "توجد واحدة أو أكثر من المطالبات المخصصة للمستخدم المقدمة لـ setCustomUserClaims() محجوزة. على سبيل المثال، لا ينبغي استخدام المطالبات الخاصة بـ OIDC مثل (sub, iat, iss, exp, aud, auth_time، إلخ) كمفاتيح للمطالبات المخصصة.",
    "auth/session-cookie-expired": "ملف تعريف الارتباط لجلسة Firebase المقدم منتهي الصلاحية.",
    "auth/session-cookie-revoked": "تم إلغاء ملف تعريف الارتباط لجلسة Firebase.",
    "auth/uid-already-exists": "معرف uid المقدّم مستخدم بالفعل من قبل مستخدم موجود. يجب أن يكون لكل مستخدم uid فريد.",
    "auth/admin-restricted-operation": "هذه العملية مقصورة على المسؤولين فقط.",
    "auth/app-not-authorized": "هذا التطبيق، الذي تم التعرف عليه بواسطة النطاق الذي يستضيفه، غير مصرح له باستخدام مصادقة Firebase مع مفتاح API المقدم. راجع تكوين المفتاح الخاص بك في وحدة التحكم Google API.",
    "auth/app-not-installed": "التطبيق المحمول المطلوب الذي يتوافق مع المعرف (اسم حزمة Android أو معرف حزمة iOS) المقدم غير مثبت على هذا الجهاز.",
    "auth/captcha-check-failed": "رمز استجابة reCAPTCHA المقدم غير صالح أو منتهي الصلاحية أو مستخدم بالفعل أو أن النطاق المرتبط به لا يتطابق مع قائمة النطاقات المصرح بها.",
    "auth/code-expired": "رمز SMS منتهي الصلاحية. يرجى إعادة إرسال رمز التحقق للمحاولة مرة أخرى.",
    "auth/cordova-not-ready": "إطار عمل Cordova غير جاهز.",
    "auth/cors-unsupported": "هذا المتصفح غير مدعوم.",
    "auth/credential-already-in-use": "هذه البيانات الاعتمادية مرتبطة بالفعل بحساب مستخدم آخر.",
    "auth/custom-token-mismatch": "الرمز المخصص يتوافق مع جمهور مختلف.",
    "auth/requires-recent-login": "تتطلب هذه العملية مصادقة حديثة. سجّل الدخول مرة أخرى قبل إعادة محاولة هذا الطلب.",
    "auth/dependent-sdk-initialized-before-auth": "تم تفعيل SDK Firebase آخر ويحاول استخدام المصادقة قبل تفعيل المصادقة. يرجى التأكد من استدعاء `initializeAuth` أو `getAuth` قبل بدء أي SDK Firebase آخر.",
    "auth/dynamic-link-not-activated": "يرجى تفعيل الروابط الديناميكية في وحدة التحكم Firebase والموافقة على الشروط والأحكام.",
    "auth/email-change-needs-verification": "يجب أن يكون لدى المستخدمين المتعددين دائمًا بريد إلكتروني موثق.",
    "auth/email-already-in-use": "عنوان البريد الإلكتروني مستخدم بالفعل من قبل حساب آخر.",
    "auth/emulator-config-failed": "تم استخدام مثيل المصادقة بالفعل لإجراء مكالمة شبكة. لا يمكن تكوين المصادقة بعد الآن لاستخدام المحاكي. حاول استدعاء 'connectAuthEmulator()' في وقت أقرب.",
    "auth/expired-action-code": "رمز الإجراء منتهي الصلاحية.",
    "auth/cancelled-popup-request": "تم إلغاء هذه العملية بسبب فتح نافذة منبثقة متعارضة أخرى.",
    "auth/internal-error": "حدث خطأ داخلي في المصادقة.",
    "auth/invalid-app-credential": "تحتوي طلب التحقق من الهاتف على مصدق تطبيق غير صالح. استجابة رمز reCAPTCHA غير صالحة أو منتهية الصلاحية.",
    "auth/invalid-app-id": "معرف التطبيق المحمول غير مسجل لمشروعك الحالي.",
      "auth/invalid-user-token": "بيانات اعتماد هذا المستخدم غير صالحة لهذا المشروع. قد يحدث هذا إذا تم العبث برمز المستخدم، أو إذا لم يكن المستخدم تابعًا للمشروع المرتبط بمفتاح API هذا.",
    
      "auth/invalid-auth-event": "حدث حدث مصادقة غير صالح. يجب تقديم أي حدث مصادقة بطريقة صحيحة. على سبيل المثال، يحدث حدث انطلاق مصادقة \"الانتهاء\" فقط بعد الحدث \"البدء\".",
    
    "auth/invalid-credential": "بيانات الاعتماد المقدمة غير صالحة.",

    "auth/missing-email": "البريد الإلكتروني مطلوب.",
    "auth/missing-credential": "مطلوب بيانات الاعتماد.",
    "auth/no-auth-event": "لا يوجد حدث مصادقة حالياً.",
    "auth/no-such-provider": "لا توجد معلومات مطلوبة لمزود مصادقة غير صالح.",
    "auth/operation-not-allowed": "تتطلب هذه العملية إعداد المصادقة من خلال البريد الإلكتروني وكلمة المرور في إعدادات Firebase.",
    "auth/operation-not-supported-in-this-environment": "هذه العملية غير مدعومة في هذا البيئة.",
    "auth/permission-denied": "تم رفض الإذن في الوصول إلى المورد.",
    "auth/user-disabled": "تم تعطيل هذا الحساب.",
    "auth/weak-password": "كلمة المرور المقدمة ضعيفة للغاية.",
    "auth/wrong-password": "كلمة المرور المدخلة غير صحيحة.",
    "auth/user-not-found": "لا يوجد مستخدم مسجل بهذا البريد الإلكتروني.", 
}
;

  return errorMessages[errorCode] || "حدث خطأ غير متوقع: " + errorCode;
}; 

export default handleFirebaseError;
